### ISSUE TITLE
Add a “Save for Later” feature

### ISSUE THREAD

**Issue by EdwardHinkle** [EdwardHinkle/indigenous-ios#100]
I think the save for later feature is actually just adding a secondary Micropub endpoint and token.

My current thinking outlined hypothetically using Aperture’s Microsub features is the following:

## ~Configuration and Saving~
- ~I go to the settings screen and I configure “Save for Later”~
- ~I enter a Micropub endpoint and an access token for that endpoint. In this case, the Micropub endpoint is built into Aperture and targets a specific channel, in my case one called “Saved”.~
- ~I enter the Micropub endpoint that I want to log in to for Save functionality. The IndieAuth flow authenticates and fetches the authentication details and saves them to be used with IndiePaper (or other future read parsing services in the future, including a private IndiePaper instance if someone has one).~
- ~I’m on a URL and I click “Save for Later”.~
- ~Indigenous parses the url for Data~
- ~Indigenous creates a Micropub request~
- ~Indigenous sends the Micropub request to the save for later endpoint~
- ~Indigenous sends the save for later authentication along with the url to save to IndiePaper~
- ~Aperture creates the new post entry in the “Saved” channel.~

Configuration and Saving options are replaced by the IndiePaper iOS app.

 ## Reading
- I open the “Saved” Channel, and read Saved posts.
- I can configure the "Saved" channel to cache posts for offline reading. (https://github.com/EdwardHinkle/indigenous-ios/issues/64)
- The Saved channel has a filter that only displays posts that are marked as “Unread”. (https://github.com/EdwardHinkle/indigenous-ios/issues/90)
- When I finish reading a post, it will be marked as unread and thus disappear because of my filters.

(Ideas unrelated to Indigenous itself: Other services can also use the Saved channel and the read/unread status to do smart things like sending a digest of my most recent unread posts from the Saved channel to Kindle, etc.)

**Comment by aaronpk** [comment]
This is a really cool idea. I think there's some good potential here, gonna need to think about this some. I'm hoping to make some more progress on this this week.

**Comment by EdwardHinkle** [comment]
@aaronpk @cleverdevil I'm not sure that adding native support in Indigenous for IndiePaper is the right step now. With https://github.com/cleverdevil/Indiepaper-macOS/pull/3 and the fact that every url in Indigenous allows you to open a ShareSheet, it doesn't make as much sense to me to bundle IndiePaper when IndiePaper (and other future services) can just have their own app in the Share Sheet.

Any thoughts for or against that train of thinking?

I think the only real outcome of this item would be being able to select a channel to have offline caching of posts.

**Comment by aaronpk** [comment]
I like the idea of just relying on the share sheet. Less hardcoding of apps!

**Comment by EdwardHinkle** [comment]
I'm going to close this issue and consider it done based on the notes above.

The remaining issues are tracked in the following issues: 
Caching Timeline Posts for Offline Reading (https://github.com/EdwardHinkle/indigenous-ios/issues/64)
Filtering a channel to only show unread posts (https://github.com/EdwardHinkle/indigenous-ios/issues/90)

**Comment by cleverdevil** [comment]
I totally agree! Share sheet via a native app extension is actually better than hardcoding it into Indigenous!
