### ISSUE TITLE
There is still a crash going on for some pages and I cannot figure...

### ISSUE THREAD

**Issue by EdwardHinkle** [EdwardHinkle/indigenous-ios#134]
There is still a crash going on for some pages and I cannot figure out what’s causing it. Right now the only page I’ve found it on is this one: <https://david-smith.org/blank.html>

When I try to use the Indigenous Share Extension, it crashes immediately.

(Originally published at: https://eddiehinkle.com/2018/03/17/16/reply/)

**Comment by zoglesby** [comment]
<a href="https://github.com/EdwardHinkle/indigenous-ios/issues/134" class="u-in-reply-to"></a>I have seen this on a few websites as well,  try an article on The Verge for example.

**Comment by EdwardHinkle** [comment]
Thanks for confirming that :)

It looks to be something with when a website is not parsable by Xray (the web site parsing service Indigenous uses). I thought I had it failing gracefully, but apparently not!

**Comment by srushe** [comment]
I’ve found that I’m reliably able to recreate the issue with the share sheet using xkcd. If I’m on an xkcd page on the `www` subdomain then the share sheet disappears after a couple of seconds, whereas when I’m on the bare `xkcd.com` domain it appears and stays (until dismissed). Your belief that it’s Xray-related definitely looks correct as Xray shows different behaviour for the 2 versions of the domain, finding the data for the bare domain, but failing for the www version.

If nothing else hopefully this makes the issue easier to replicate.

**Comment by EdwardHinkle** [comment]
Thanks! That’s helpful. This error is a pretty big priority so I’m gonna try to wrap it up in this next version
