### ISSUE TITLE
Accept HTTP 202 status for creating new posts

### ISSUE THREAD

**Issue by martymcguire** [EdwardHinkle/indigenous-ios#139]
My micropub endpoint creates posts asynchronously. Indigenous reports this as an error and has to be cleared afterwards.

![f8de12a1-4588-4945-a98e-09635b2c0983](https://user-images.githubusercontent.com/14772/37855898-0a618f1a-2ec8-11e8-8924-11373ba8e530.png)

**Comment by EdwardHinkle** [comment]
Oops! I put that into the next build!

**Comment by martymcguire** [comment]
🎉
