### ISSUE TITLE
Add user agent to http requests

### ISSUE THREAD

**Issue by EdwardHinkle** [EdwardHinkle/indigenous-ios#145]
Should be name, version number and url of app

**Comment by aaronpk** [comment]
Usually it'll look something like `Indigenous/1.0.0` before the other system user agent strings like iOS version

**Comment by EdwardHinkle** [comment]
@aaronpk Is there an easy way to test this? I've never looked up User Agent strings on my server logs or anything?

**Comment by aaronpk** [comment]
If you can find your normal web server access logs they should be there. Usually it's part of what's logged by default. Otherwise if you want to point it at mine I can check for you.

**Comment by EdwardHinkle** [comment]
It is currently: Indigenous/0.2.4 x86_64 iOS/11.3 CFNetwork/897.15 Darwin/17.4.0

**Comment by EdwardHinkle** [comment]
Ohhh, I should remove the x86_64, that was a depreciated function
So it will look like: Indigenous/0.2.4 iOS/11.3 CFNetwork/897.15 Darwin/17.4.0

**Comment by aaronpk** [comment]
Great! I look forward to seeing this in my logs!
