### ISSUE TITLE
macOS version

### ISSUE THREAD

**Issue by gerwitz** [EdwardHinkle/indigenous-ios#154]
I know this is a stretch, but I would love to have the sharing sheet as a macOS extension … and the rest of Indigenous would be pretty sweet, too.

**Comment by EdwardHinkle** [comment]
Definitely something I want to do. I miss it all the time. I haven’t done any macOS programming before. I’m hoping for something from WWDC but the rumors seem like that multi-platform is at earliest a year off so I might just have to look into it

**Comment by EdwardHinkle** [comment]
I might attempt a Share Extension this fall, but the real app will happen in 2018 when Apple adds the new ability for iOS apps to be ported to the mac

**Comment by EdwardHinkle** [comment]
This will be covered by "Marzipan" for the new apps when it comes out this fall.
