### ISSUE TITLE
Extra file on indigenous.abode.pub for Android

### ISSUE THREAD

**Issue by swentel** [EdwardHinkle/indigenous-ios#172]
I didn't know exactly where to put the issue, so I opened it here.

I'm refactoring the authentication part in the Android app to support multiple accounts and not use the internal browser. For that I need something extra on a domain to trigger the app once the authentication has happened (usually on indieauth.com, but that doesn't matter in the end).

I have it working, but I guess it might be more interesting to host this on https://indigenous.abode.pub/ as it's the central place then for the Indigenous apps. I have a PHP file, but I'm not sure if that is supported on that server ? :)

It currently runs in a file called 'indigenous-android.php' - maybe the path could become something like /oauth/android', that's even cleaner :)

This is the code.

```php
<?php
$code = isset($_GET['code']) ? $_GET['code'] : '';
$state = isset($_GET['state']) ? $_GET['state'] : '';
$url = 'indigenous-android://oauthcallback?code=' . $code . '&state=' . $state;
?>
<html>
<head>
  <title>Indigenous Android</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="refresh" content="0; url=<?php print $url; ?>" />
</head>
<body>

Indigenous OAuth Sign in.
<br /><br />
If Indigenous is not opening, <a href="<?php echo $url; ?>">click here</a>

</body>
</html>

```

**Comment by swentel** [comment]
Apart from that, I have a new release now to support those multiple accounts, but it requires me to have a privacy policy. We'll have to add something on that domain there too.

**Comment by EdwardHinkle** [comment]
Sounds good, I should probably have a privacy policy up there for iOS too since I’m hoping to publish it later this month in the app store

**Comment by EdwardHinkle** [comment]
I realized this is really just a redirect, so I set up an nginx level redirect rather than using the PHP file. Prevents waiting for the browser refresh. The URL you can use to get the android callback is: `https://indigenous.abode.pub/android/login/`

**Comment by EdwardHinkle** [comment]
The Privacy Policy, etc can be tracked in #225

**Comment by swentel** [comment]
Cool works, thanks!
