### ISSUE TITLE
Share Sheet mysteriously aborts on some URLs

### ISSUE THREAD

**Issue by martymcguire** [EdwardHinkle/indigenous-ios#174]
When trying to share some URLs from Safari (e.g. [this one](http://www.kimblery.com/2018/06/08/here-again/)), the Share Sheet will appear, but then quickly disappear before I can select an option.

The page in question doesn't have proper microformats, so that could be an issue if Indigenous is trying to do any pre-processing. However, sending a Like only needs the URL, for example. :}

**Comment by EdwardHinkle** [comment]
Thanks 🙂 I have the bug fix for this ready but the next build has been blocked by some other bugs. Lol I’m hoping to get those new bugs fixed so I can push out this build and get this issue fixed
