### ISSUE TITLE
Issues with logging in

### ISSUE THREAD

**Issue by vishae** [EdwardHinkle/indigenous-ios#195]
I enter my domain name (https://www.serenawho.com) and log into my WordPress site. The next page that loads asks me to authorise the app, but gives me a warning:

>**Warning:** The redirect URL this app is using does not match the domain of the client ID.

I click Authorise anyway and it takes me back to my WordPress login page with the error:
>IndieAuth Server did not return the same state parameter

Am I doing something wrong?

**Comment by EdwardHinkle** [comment]
I have run into this error on my Test instance of Wordpress. I think there is something wrong with the Wordpress IndieAuth plug-in, but I am looking into this. Thanks for letting me know you are seeing it as well. Helps to know how wide-spread the issue is

**Comment by aaronpk** [comment]
We've gone through a bunch of bugfixes on the Wordpress plugin. Just to confirm, is this using the current published version of the IndieAuth plugin?

**Comment by vishae** [comment]
yes @aaronpk I am using the latest IndieAuth plugin.

**Comment by vishae** [comment]
Just confirming, there's nothing that I can do on my end to fix the issue?

**Comment by EdwardHinkle** [comment]
Thanks for confirming. Unfortunately there seems to be something strange going on between the IndieAuth sessions and iOS’s web login mechanism. I’m investigating and I’ll let you know when I figure out what’s going on. But I would say 99% it’s either the plug-in itself or it’s my app. So nope, nothing for you to do 🙂

**Comment by EdwardHinkle** [comment]
@vishae If you don’t mind, can you delete the beta and download the version that’s been released on the App Store? I’ve been hearing reports that the latest build on the App Store has fixed most (if not all) of the login issues

**Comment by vishae** [comment]
I can confirm that the latest version of the app has fixed the login issue. Thanks!

**Comment by EdwardHinkle** [comment]
Yay!!
