### ISSUE TITLE
Login needs to follow redirects (http -> https)

### ISSUE THREAD

**Issue by EdwardHinkle** [EdwardHinkle/indigenous-ios#20]
When trying to log in to http://cleverdevil.io, it doesn’t follow the redirect to https://cleverdevil.io so we just get stuck in the endless spinner

**Comment by miklb** [comment]
I may be experiencing this issue as well, as I'm stuck on the `Authorizing server` screen.

**Comment by aaronpk** [comment]
I had this problem too. The UI suggests I should enter just my domain name. If I enter the full URL including https, then it continues fine.

**Comment by EdwardHinkle** [comment]
I need to implement a urlSession delegate in order to confirm the redirection.

Notes for dev:
https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/URLLoadingSystem/Articles/RequestChanges.html
https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/1411626-urlsession
https://stackoverflow.com/a/29071667

**Comment by miklb** [comment]
FWIW, after updating to build-5 I was showing as logged in at `http` and had to log out and back in and explicitly use `https` otherwise my micropub request for a like silently failed.

**Comment by EdwardHinkle** [comment]
Hmm, definitely not expected behavior. I'll look into this

**Comment by aaronpk** [comment]
I entered `aaronparecki.com` and it looks like I'm logged in as `https://aaronparecki.com/`.

@miklb do you know if your IndieAuth server returns `me=https://miklb.com` or `http://miklb.com`? This app should be using whatever the final `me` value is returned.

**Comment by miklb** [comment]
> do you know if your IndieAuth server returns me=https://miklb.com or http://miklb.com? This app should be using whatever the final me value is returned.

I do not know. I'm using the WordPress IndieAuth plugin.

@aaronpk suggestion on how I can check?

**Comment by EdwardHinkle** [comment]
It actually looks like this is on me. I use the URL you enter rather than the ME that is returned from IndieAuth. That is likely the problem. I can fix this in the next build
