### ISSUE TITLE
Login state is not retained

### ISSUE THREAD

**Issue by dg01d** [EdwardHinkle/indigenous-ios#21]
Hi Eddie,

I open Indigenuous, get the login screen. I enter the site address, https://ascraeus.org/, and get the redirect to IndieAuth, that's all fine.

After logging into a designated provider, the program exits. On relaunch, the screen briefly flashes logged in as - then resets to the login screen.

iOS 11, iPhone 6

**Comment by EdwardHinkle** [comment]
Thanks for letting me know!

This is likely a duplicate of #23 so I'll close this for now :)
