### ISSUE TITLE
Unable to add new Micropub account

### ISSUE THREAD

**Issue by skpy** [EdwardHinkle/indigenous-ios#213]
I'm trying to add another Micropub account to my Indigenous for iOS install.  I've successfully authenticated, but Indigenous is just showing a spinner on the "Authorizing with Server" screen.

I've confirmed that I can log into my site via indieauth.com.

**Comment by EdwardHinkle** [comment]
Hmmm, strange. What software or service powers the second Micropub server? Micro.blog, Wordpress, etc?

**Comment by skpy** [comment]
Both sites ([primary](https://skippy.net/), [secondary](https://skippy.is/)) are my own static sites powered by Hugo, using [my own PHP Micropub](https://github.com/skpy/micropub) server, and [selfauth](https://github.com/inklings-io/selfauth/) for authentication.

I see now that the second site does show up as an account within Indigenous.  I haven't tried posting to it yet; but the Indigenous debug info does show an access token, my media endpoint, and syndication targets.  I'll give this a test soon-ish and report back.

**Comment by EdwardHinkle** [comment]
So it looked like it just got stuck on authorizing, but it did in fact get added? So the issue is not one of it functioning as much as the UI not updating properly

**Comment by skpy** [comment]
This is not a pressing issue for me, so closing.
