### ISSUE TITLE
Get error 403 when accessing Wordpress blog 

### ISSUE THREAD

**Issue by seishonagon** [EdwardHinkle/indigenous-ios#220]
My wordpress setup (4.9.8) has the latest indieAuth plugin and seems well set up.
I have a github rel=me link in  the head
When I try to login to the site within Indigenous I get an error 403, and I don’t know what else to do ...

**Comment by EdwardHinkle** [comment]
What’s your site’s URL?

**Comment by seishonagon** [comment]
https://paulatlan.net

--  
Paul Atlan  
+33 (0) 7 82 62 60 35(tel:+33%207%2082%2062%2060%2035)

**Comment by EdwardHinkle** [comment]
Hmmm, everything I can see without logging in as you seems like things are working correctly. I see all the endpoints and such that I'm looking for.

At what point during the steps do you get a 403 error? When I enter your URL into Indigenous I get to a login screen on your Wordpress site. I'm assuming you enter your credentials and continue from there. What is the last thing you see before you get the 403?

**Comment by EdwardHinkle** [comment]
403 error with Wordpress blogs is a common IndieWeb WordPress error. With this PR (https://github.com/indieweb/wordpress-indieauth/pull/136) hopefully Wordpress will surface the error and help fix it
