### ISSUE TITLE
Put together Android website

### ISSUE THREAD

**Issue by EdwardHinkle** [EdwardHinkle/indigenous-ios#225]

**Comment by EdwardHinkle** [comment]
@swentel I'm happy to put up a website for Android that looks like the one for iOS. I just need a couple of things from you.

If you look at https://indigenous.abode.pub/ios/

I need 4 screenshots of the Android app. They can show whatever you want, but we'll put them in the same spots as the iOS ones. In place of the Download icon I can add a "Sign up for the beta" link. I'll just need the link for signing up for the beta.

I have a basic privacy policy in place of iOS here (https://indigenous.abode.pub/ios/privacy/) we can essentially copy that over to /android/privacy/ for you. But feel free to make notes in here about what changes you would like to make to it here.

Once I get both the websites up, I'll create repos for them so you can just create pull requests in the future to update the website however you want for Android, then I can just merge the new code onto the server.

I can also provide the https://indigenous.abode.pub/ios/help/ for android as well. I don't think that should need any updates currently as all of that is about IndieWeb tech, not iOS or Android.

**Comment by EdwardHinkle** [comment]
On second thought, I just made the repo: https://github.com/EdwardHinkle/indigenous-website

Feel free to make any changes you want to the android folder and open a PR :) I'll merge it into the site

**Comment by swentel** [comment]
Wow, that's beautiful!

One detail on the help page re: the Drupal plugin: it doesn't allow you yet to use your own site to authenticate via IndieAuth. What's possible right now is to register/login to a drupal site via indieauth.com (or another service) (I'm working on that functionality though, coming hopefully soon)

I hope to get location in soon on the Android client, and then I will probably go public, even though I don't have all features yet as the iOS.

**Comment by EdwardHinkle** [comment]
Ohhh I didn't realize. I'll make that change to the Drupal text
