### ISSUE TITLE
Crashes after approving authorization

### ISSUE THREAD

**Issue by aaronpk** [EdwardHinkle/indigenous-ios#23]
After I approve the authorization from my site, the app crashes. 

I dug up the logs, and here's where it crashed:

```
Indigenous(CoreFoundation)[14432] <Notice>: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'accessing _cachedSystemAnimationFence requires the main thread'
```

**Comment by EdwardHinkle** [comment]
Ah, looks like it was a hidden multi-threading glitch. I obviously wasn't logging in and out a bunch on my machine so I just happened to get lucky and it executed the login the couple of times I did it on the main thread.

Should be a pretty simple fix this weekend and 🤞 hopefully we'll have it pushed out to TestFlight quickly

**Comment by EdwardHinkle** [comment]
This should be fixed in commit: https://github.com/EdwardHinkle/indigenous-ios/commit/83a826d7b60394ee2636e7ec4996b3c86c17c231
