### ISSUE TITLE
black on black text [bug]

### ISSUE THREAD

**Issue by vipickering** [EdwardHinkle/indigenous-ios#239]
1. Switching to dark mode theme
2. type a post and add a tag so the title appears
3. Type the text in the title and it will be black on black instead of white on black.

This works on the light theme as intended.

**Comment by RosemaryOrchard** [comment]
Related to this (I think/hope), when switching to the dark theme, the light theme text gets blacked out.
![IMG_1581](https://user-images.githubusercontent.com/16113535/57212748-f9760a00-6fe4-11e9-9053-ee216ab66d83.PNG)

**Comment by EdwardHinkle** [comment]
Thanks. With Indigenous splitting into several different apps, this mostly relates to Remark, the new Social Reader app being built. I'm going to be taking a new tactic toward theming in Remark (https://github.com/EdwardHinkle/remark/issues/53) and it should prevent these glitches
