### ISSUE TITLE
Unable to view read entries

### ISSUE THREAD

**Issue by RosemaryOrchard** [EdwardHinkle/indigenous-ios#246]
I may be missing something (please tell me if I am), but Indigenous on my iPhone does not allow me to view read articles as far as I can tell - I would love to be able to do this to be able to go back and find a previously read article, and also for demo purposes.

**Comment by EdwardHinkle** [comment]
Oh you can set it to view all posts by tapping the filter button inside the search field

**Comment by EdwardHinkle** [comment]
Looks like this might be a case of some authentication error that wasn't surfaced correctly. That will be fixed in future versions :) But I will close this since it wasn't as much about the filter having an issue.
