### ISSUE TITLE
User customisable post types

### ISSUE THREAD

**Issue by colin-walker** [EdwardHinkle/indigenous-ios#31]
Add the ability to customise the post types, e.g. change note to status for WordPress users.

**Comment by aaronpk** [comment]
what do you mean "status"? The Micropub spec doesn't define post types, so there isn't anything there called a "note".

**Comment by colin-walker** [comment]
My bad, I thought used article & note.
Posting a like to WordPress using Ingenious seemed to go through as a standard post so I thought something wasn’t lining up as I use WordPress post formats.

**Comment by EdwardHinkle** [comment]
I'm not super familar with WordPress post formats, but I would think having the like-of property should transform into a Like post type?

**Comment by aaronpk** [comment]
Indigenous only posts "like-of" and "bookmark-of" right now, right?

**Comment by EdwardHinkle** [comment]
Correct. "like-of", "bookmark-of" and "repost-of" currently.

Replies and Notes are scheduled for the next build.

Articles a little further down the road.

**Comment by EdwardHinkle** [comment]
@colin-walker Are you using a specific plugin for your micropub endpoint?

**Comment by colin-walker** [comment]
Got it. So, I’ll have to do something on my end to change the post format when submitted.

**Comment by colin-walker** [comment]
I’m using Snarfed’s plugin.

**Comment by colin-walker** [comment]
I'll close this. I've added a function to my site to change the WordPress post format.
