### ISSUE TITLE
Syndicate reply to micro.blog 

### ISSUE THREAD

**Issue by EdwardHinkle** [EdwardHinkle/indigenous-ios#58]
When posting a reply to a non-micro.blog hosted site, there should be an option to syndicate replies to micro.blog.

In order for this to happen outside of a native micro.blog post, I'll need an API from manton that allows me to provide a URL and get the micro.blog API id back.

**Comment by aaronpk** [comment]
Shouldn't micro.blog be able to figure this out server side? If your reply is in your feed that micro.blog is crawling then it would know about the post that way and should be able to match it up. I think this would be best solved without requiring user interaction. Maybe I'm missing some of the context of this tho? Could you provide an example of the situation with links?

**Comment by EdwardHinkle** [comment]
Well currently micro.blog doesn’t recognize external replies so right now I have to use the micro.blog app/api to get a reply into the system. When micro.blog recognizes replies in your feed, this will become not needed

**Comment by EdwardHinkle** [comment]
Correction: it accepts replies to anything in a micro.blog hosted site. So any original content on a micro.blog site or a reply hosted by micro.blog. The issue is when you externally (eddiehinkle.com) want to reply to an external post (Colinwalker.com) or an external reply (aaronparecki.com) but you want the reply to be funneled through micro.blog. The missing piece is micro.blog catching a “in-reply-to” microformat in the feed content and turning that into a native reply. From what I understand that is on manton’s list but I don’t know what the timetable (haha) is for that.

**Comment by EdwardHinkle** [comment]
This is mostly resolved already. Not going to pursue this
