### ISSUE TITLE
Every post should be marked as read after it is interacted with in some way.

### ISSUE THREAD

**Issue by EdwardHinkle** [EdwardHinkle/indigenous-ios#72]
Each post (unique id as URL, so the same post might be in multiple channels.) should track certain things such as what types of responses the user has done. It should also remember if the post has been “read”. When it’s read it should be slightly dimmed from view. If the user views a photo, opens a longer version of a post, or responds to the post in some way, it should be marked as read.

It should also be able to be unmarked as read.

**Comment by aaronpk** [comment]
There are some notes in the brainstorming section about storing this sort of per-item state on the server. Is this something you're planning on doing strictly client-side, or would you also want to push that state to the server? https://indieweb.org/Microsub-spec#Brainstorming

**Comment by EdwardHinkle** [comment]
I would love to push this information to the server

**Comment by EdwardHinkle** [comment]
This currently happens when a user view's a post's full view or when you reply to a post.

Posts should also be marked as read when the response bar is used to respond to the post. (#125)

**Comment by EdwardHinkle** [comment]
There should also be an option to "auto-read" a post as it scrolls of the page

**Comment by EdwardHinkle** [comment]
There is a bug in how I currently deal with auto-mark as read. I need to find out how to link it ONLY to scrolling. Right now if the view is removed off screen, it marks all the posts as read

**Comment by EdwardHinkle** [comment]
Also: Steal Monocle’s functionality of marking all visible items as read when you scroll to the VERY bottom of the page.

**Comment by skpy** [comment]
While scrolling to the bottom to mark "read" is good, there are also times when I'm reading a long article and decide "I'm done with this."  If it's an exceptionally long article, I'd rather just click a "mark as read" icon rather than scroll to the bottom.

**Comment by EdwardHinkle** [comment]
Yes, I definitely want a “mark as read/unread” that is available on both the timeline’s menu AND the full screen reading view
