### ISSUE TITLE
A channel should have some type of a subtle indicator if there are “new posts”

### ISSUE THREAD

**Issue by EdwardHinkle** [EdwardHinkle/indigenous-ios#73]
Need to determine what a “new post” is. Is it posts after the current “timeline location”? I don’t think that’s the case because that means scrolling down would cause the indicator to appear.

The easiest way seems to be when your timeline reaches the top of the channel, it sets the channel as read. When a background fetch happens, if it discovers new posts by using the “before” Microsub token, then it should set the channel to “new”. This means a channel is “read” not if everything is read, but if the timeline has been scrolled to the top.

**Comment by aaronpk** [comment]
Do you need something new from the Microsub server to accomplish this?

**Comment by EdwardHinkle** [comment]
Not necessarily. I will be storing the “before” token so that in the background I can periodically fetch new items. That can definitely all take place with the current implementation.

The one thing that *might* be helpful, but I don’t know if we have enough use cases to make a case for it yet, would be if you could pass a before token and if the server responded with how many new items there were, not paginated. If there were 50 new items, currently I would have to keep fetching the items in the background using the before token until I reached 0 items returned, at which point I would know I have all the items, but with something like that you could make a pretty light weight query and get the total number of items to expect with a single query.

The usefulness over just fetching a couple of times? I’m not sure it’s proven itself enough to be implemented yet.

**Comment by EdwardHinkle** [comment]
The challenge is that assumes someone will read EVERY post before it becomes "Not read". If I skim a long string of posts and scroll to the top, I want that to essentially be a "post bankruptcy". I don't actually want to mark all those posts as read but I definitely want to make the channel as read.

I think using that page you linked to, the best option might be comparing the last updated date from the existing data to the last updated date from the periodic channel fetch. This is assuming the last updated date would only update when a new post is added to a channel. Does that seem like a reasonable expectation?

**Comment by aaronpk** [comment]
(Just moved all the brainstorming from the wiki to github issues so it's easier to link to. Here is the previously referenced thread: https://github.com/indieweb/microsub/issues/10)

and yeah the idea with the `updated` property is it would be updated whenever a new item is added to the channel.

**Comment by EdwardHinkle** [comment]
Excellent. I think the "unread counts" property is useful based on common reader approaches. So I think that is definitely valuable, I can see a lot of people wanting to use that. For my use-case, my unread status will likely be based on if the updated property has been "updated".

I'm gonna have to think about this further because there are three options I could do. Regardless of the option I use, Indigenous' default will always be based on if new posts have come in. However, there are some additional features I might implement:

- I could provide an account-wide setting that changes all Channel Unread indicators to be based on if there are any unread posts in the channel. This would be helpful for people that are completionists.
- One potentially interesting idea is instead of the above option, I could provide a per-channel setting of the "Unread Status" of the channel. This would be helpful because some channels I might want to read completely (more article based channels), whereas other channels I might want to be able to just scroll to the top and only have it be marked as unread when a new post comes in.

I think I'm learning towards that last approach:
- All channels default to showing as read when the user has scrolled to the top and showing as unread when the channel has been updated with at least one new post.
- Each channel can be edited to have it's read/unread indicator be based on if there are any unread posts in the channel.

**Comment by aaronpk** [comment]
I like it. I'm definitely planning on having a few channels that I want to read 100% of the posts, and some where I want to skim them really quick, so I would definitely use that setting.
