### ISSUE TITLE
Autocomplete covers UI elements 

### ISSUE THREAD

**Issue by aaronpk** [EdwardHinkle/indigenous-ios#74]
![d7ed0314-eb6a-41a7-ac45-9f86e69b474b](https://user-images.githubusercontent.com/113001/35493172-40a95fe4-0466-11e8-8dfc-bb54bd5d88b2.png)

**Comment by EdwardHinkle** [comment]
That’s very interesting. There must be some difference between iPhone X and traditional iPhones that’s causing this. There are currently two reports of this. Hopefully should be a simple fix to push

**Comment by EdwardHinkle** [comment]
Fixed in this commit: https://github.com/EdwardHinkle/indigenous-ios/commit/039c6738bbbc1278ce361bfb1e094b782fe02784
