### ISSUE TITLE
Swipe to view should immediately launch the browser

### ISSUE THREAD

**Issue by aaronpk** [EdwardHinkle/indigenous-ios#76]
I don't think the extra step of swipe then click is needed. Would be nicer if the swipe action was all that was needed to open the browser

**Comment by EdwardHinkle** [comment]
I believe this should work. I do it all the time. You might need to swipe just a _little_ further?

**Comment by aaronpk** [comment]
hah you're right! That was farther than I expected. Also the fact that it swings back and the "view" button stays visible made me think there wasn't any farther I could swipe.

**Comment by EdwardHinkle** [comment]
Ahhh yeah. Sometimes I do feel like the default TableView swipes require a bit further of a swipe. I like using the native controls, so I don't know how much I want to modify it, but I'll have to see if there is some way that I can use the native controls but "tweak" the swipe length required for a full swipe.

**Comment by aaronpk** [comment]
oh cool, didn't even know that was a built in control now!

**Comment by EdwardHinkle** [comment]
Yeah, it's pretty awesome. You it is just to delegate methods that your TableView delegate calls. You override the methods and return the options.
