### ISSUE TITLE
Crash when refreshing channel list

### ISSUE THREAD

**Issue by aaronpk** [EdwardHinkle/indigenous-ios#79]
I encountered a crash when I did the pull to refresh gesture in the channel list. I doesn't crash every time, so I'm not quite sure what the combination of things was to cause it. I don't see any crash info in my device logs.

**Comment by EdwardHinkle** [comment]
Diagnosing Info:

The crash info:
`#0	(null) in _T010Indigenous21ChannelViewControllerC05tableC0So07UITableC4CellCSo0fC0C_10Foundation9IndexPathV12cellForRowAttFTf4ggn_n ()`

Seems to be pointing over here: https://github.com/EdwardHinkle/indigenous-ios/blob/5eef2f8a95802be29cb364bdfdbb7120bb32b091/Indigenous/App/Reader/Channel/ChannelViewController.swift#L44
